name: 'Hackathon'
on: [push]

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    outputs:
      aks: ${{ steps.tfout.outputs.aks }}
      rg: ${{ steps.tfout.outputs.rg }}
      acr_name: ${{ steps.tfout.outputs.acr_name }}
      acr_url: ${{ steps.tfout.outputs.acr_url }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v1

    - run: terraform init
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -out=terraform.tfplan

    - name: Terraform Apply
      id: apply
      # if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -no-color terraform.tfplan

    - name: Terraform Outputs
      id: tfout
      run: |
        tf=$(terraform output -no-color -json)
        echo "::set-output name=rg::$(echo $tf | jq -r .resource_group_name.value)"
        echo "::set-output name=aks::$(echo $tf | jq -r .aks_name)"
        echo "::set-output name=acr_name::$(echo $tf | jq -r .acr_name)"
        echo "::set-output name=acr_url::$(echo $tf | jq -r .acr_url)"

  container:
    name: 'Container Build'
    needs: terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./container
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Docker Login to Registry
        run: |
          az acr login --name ${{ needs.terraform.outputs.acr_name }}

      - name: Build
        run: docker build -t ${{ needs.terraform.outputs.acr_url }}/nginx:latest .

      - name: Push
        run: docker push ${{ needs.terraform.outputs.acr_url }}/nginx:latest

  kubernetes:
    name: 'Kubernetes'
    needs: terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./kubernetes
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environemnt
        run: |
          az aks get-credentials --resource-group ${{ needs.terraform.outputs.rg }} --name ${{ needs.terraform.outputs.aks }}

      - name: Deploy Manifests
        run: |
          kubectl apply -f deployment.yaml -f service.yaml
