name: 'Stage 4 Frontend Backend'
on: [workflow_dispatch]


jobs:
  container:
    name: 'Container Build'
    needs: terraform
    runs-on: ubuntu-latest
    environment: production
    
    env:
      registryName: "2021hackathon"
      registryLoginServer: "myregistrysy.azurecr.io"

    defaults:
      run:
        shell: bash
        #working-directory: ./container
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Docker Login to Registry
        run: |
          az acr login --name ${{ env.registryName }}
        
      # Build Frontend
      - name: Build Frontend
        run: docker build -t ${{ env.registryLoginServer }}/frontend-nginx:latest ./stage_4_Frontend_Backend/frontend

      - name: Push Frontend
        run: docker push ${{ env.registryLoginServer }}/frontend-nginx:latest

      # Build Java Example Backend
      - name: Build Java Example Backend
        run: docker build -t ${{ env.registryLoginServer }}/java-docker-backend-example:latest ./stage_4_Frontend_Backend/backend/java-docker

      - name: Push Java Example Backend
        run: docker push ${{ env.registryLoginServer }}/java-docker-backend-example:latest

      # Build Golang Example Backend
      - name: Build Go Example Backend
        run: docker build -t ${{ env.registryLoginServer }}/go-docker-backend-example:latest ./stage_4_Frontend_Backend/backend/go-docker

      - name: Push Go Example Backend
        run: docker push ${{ env.registryLoginServer }}/go-docker-backend-example:latest

