name: 'Stage 3 Single Container'
on: [workflow_dispatch]


jobs:
  container:
    name: 'Container Build'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      registryName: "2021hackathon"
      registryLoginServer: "2021hackathon.azurecr.io"

    defaults:
      run:
        shell: bash
        #working-directory: ./container
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Docker Login to Registry
        run: |
          az acr login --name ${{ env.registryName }}

      # Build Old NGINX Frontend
      - name: Build NGINX Base Frontend
        run: docker build -t ${{ env.registryLoginServer }}/nginx:latest ./stage_3_SingleContainer

      - name: Push NGINX Base Frontend
        run: docker push ${{ env.registryLoginServer }}/nginx:latest

      - name: Deploy Manifests
        run: |
          kubectl apply -f ./stage_3_SingleContainer/